# Copyright (c) 2024, Hershel Theodore Layton
# Copies of this file can be made, with or without changes,
# under the terms of the MIT-0 license.

name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Run every day at 6:04PM (before any other test suites)
    - cron: "04 18 * * *"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}}
    strategy:
      fail-fast: false
      matrix:
        hhvm:
          - "4.128"
          - "4.153"
          - "4.168"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create branch for version alias
        run: git checkout -b CI_current_pull_request
      - uses: hershel-theodore-layton/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          # We just want to run hh_client, nothing to lint, nothing to test
          skip_lint: true
          skip_tests: true
